package de.iils.dc43.plotplugin.views;

import java.awt.Frame;
import java.util.Map.Entry;

import org.eclipse.jface.action.Action;
import org.eclipse.jface.action.IAction;
import org.eclipse.jface.action.IMenuCreator;
import org.eclipse.jface.action.IToolBarManager;
import org.eclipse.swt.SWT;
import org.eclipse.swt.awt.SWT_AWT;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.events.SelectionListener;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.MenuItem;
import org.eclipse.ui.part.ViewPart;
import org.math.plot.Plot2DPanel;

import de.iils.dc43.plotplugin.plots.MenuCollection;
import de.iils.dc43.plotplugin.plots.PlotDatabase;
import de.iils.dc43.plotplugin.plots.PlotFactory;

/**
 * This sample class demonstrates how to plug-in a new workbench view. The view
 * shows data obtained from the model. The sample creates a dummy model on the
 * fly, but a real implementation would connect to the model available either in
 * this or another plug-in (e.g. the workspace). The view is connected to the
 * model using a content provider.
 * <p>
 * The view uses a label provider to define how model objects should be
 * presented in the view. Each view can present the same model objects using
 * different labels and icons, if needed. Alternatively, a single label provider
 * can be shared between views in order to ensure that objects of the same type
 * are presented in the same way everywhere.
 * <p>
 */

public class PlotPluginView extends ViewPart {

	/**
	 * The ID of the view as specified by the extension.
	 */
	public static final String ID = "de.iils.dc43.plotplugin.views.PlotPluginView";

	private Frame frame;
	private Label label;

	private DropDownAction xValueDownMenu;
	private DropDownAction yValueDownMenu;

	private MenuCollection menuCollection;

	private Plot2DPanel active2DPlot;

	/*
	 * The content provider class is responsible for providing objects to the
	 * view. It can wrap existing objects in adapters or simply return objects
	 * as-is. These objects may be sensitive to the current input of the view,
	 * or ignore it and always show the same content (like Task List, for
	 * example).
	 */

	/**
	 * The constructor.
	 */
	public PlotPluginView() {
	}

	/**
	 * This is a callback that will allow us to create the viewer and initialize
	 * it.
	 */
	@Override
	public void createPartControl(Composite parent) {
		Composite composite = new Composite(parent, SWT.EMBEDDED | SWT.NO_BACKGROUND);
		frame = SWT_AWT.new_Frame(composite);

		// Update DB
		PlotDatabase.getDatabase().updateFromFile(
				"F:\\Documents\\Uni\\masterarbeit\\AutoGeneratedMacros\\sensor1.tab", " ");

		// Constructor for Plot
		active2DPlot = PlotFactory.create2DStandardPlot();
		frame.add(active2DPlot);

		// Toolbar
		createToolBar();

	}

	// private void samplePlot(Composite composite) {
	// Plot2DPanel plot;
	// try {
	// PlotDatabase.getDatabase().updateFromFile(
	// "F:\\Documents\\Uni\\masterarbeit\\AutoGeneratedMacros\\sensor1.tab",
	// " ");
	// plot = PlotFactory.create2DPlotWithAllData("Time-Time");
	// frame = SWT_AWT.new_Frame(composite);
	// frame.add(plot);
	// plot.addLegend(plot.SOUTH);
	//
	// } catch (NoSuchFieldException e) {
	// e.printStackTrace();
	// }
	// }

	private void createToolBar() {

		menuCollection = new MenuCollection(PlotDatabase.getDatabase().getAllDBKeys());

		xValueDownMenu = new DropDownAction("X-Value", menuCollection, 0);
		yValueDownMenu = new DropDownAction("Y-Value[s]", menuCollection, 1);

		IToolBarManager toolBar = getViewSite().getActionBars().getToolBarManager();
		toolBar.add(xValueDownMenu);
		toolBar.add(yValueDownMenu);

	}

	@Override
	public void dispose() {
		super.dispose();
		// frame.dispose();
	}

	/**
	 * Passing the focus request to the viewer's control.
	 */
	@Override
	public void setFocus() {
		System.out.println("Focused");
	}

	class DropDownAction extends Action {
		public DropDownAction(String name, final MenuCollection menuCollection, final int column) {
			super(name, IAction.AS_DROP_DOWN_MENU);

			setMenuCreator(new IMenuCreator() {
				@Override
				public Menu getMenu(Control parent) {
					Menu menu = new Menu(parent);

					for (final Entry<String, Boolean[]> entry : menuCollection.getStore()
							.entrySet()) {
						final MenuItem item = new MenuItem(menu, SWT.CHECK);
						item.setText(entry.getKey());
						item.setSelection(entry.getValue()[column]);
						item.addSelectionListener(new SelectionListener() {

							@Override
							public void widgetSelected(SelectionEvent e) {
								menuCollection.showValue(entry.getKey(), column);

								// Update 2DPlot View
								// try {
								// active2DPlot =
								// PlotFactory.create2DPlotByVariableNames(
								// menuCollection.getXVariableName(),
								// menuCollection.getYVariableNames());
								// } catch (NoSuchFieldException e1) {
								// e1.printStackTrace();
								// }
							}

							@Override
							public void widgetDefaultSelected(SelectionEvent e) {

							}
						});
					}

					return menu;
				}

				@Override
				public Menu getMenu(Menu parent) {
					return null;
				}

				@Override
				public void dispose() {
				}
			});
		}

		@Override
		public void run() {
		}
	}
}